### ISSUE TITLE
Bug: Log produces errors when DoorSense is not configured/in use. "Lock: Front Door doorState: init, closed: false, open: false"

### ISSUE THREAD

**Issue by hrhnick** [homebridge-plugins/homebridge-august#21]
### Describe The Bug

I use a thread based door sensor for automations as it is much faster than the August DoorSense, therefore I attempted to remove the DoorSense from my August setup. Log produces errors when DoorSense is not configured/in use. "Lock: Front Door doorState: init, closed: false, open: false" Issue persists if plugin is configured to hide sensor.

### To Reproduce

Remove DoorSense from lock setup in August app so no DoorSense is detected.

### Expected behavior

No error is reported if there is no DoorSense. (Or a one time log notification on startup)

### Relevant log output

```shell
[10/11/2022, 11:05:00 AM] [August] Lock: Front Door doorState: init, closed: false, open: false
```

### Config for homebridge-august

```shell
"name": "August",
            "credentials": {
                "augustId": "xxxxx@xxxxxx.com",
                "password": "xxxxxx",
                "validateCode": "xxxxx",
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "logging": "standard"
            },
            "platform": "August"
```

### Screenshots

<img width="873" alt="Screenshot 2022-10-11 at 11 05 02 AM" src="https://user-images.githubusercontent.com/223259/195128593-5e685489-7b1f-4c39-91d9-5115c6cae843.png">

### Device & Model

August WiFi Smart Lock

### Node.js Version

16.17.1

### NPM Version

8.5.0

### Homebridge Version

oznu/homebridge:latest

### Homebridge August Plugin Version

1.0.5

### Homebridge Config UI X Plugin Version

4.50.1

### Operating System

Docker

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-august@beta/>=v1.0.6-beta.1/orange)](https://www.npmjs.com/package/homebridge-august)

[Click here to find out how to install Beta](https://github.com/donavanbecker/homebridge-august/wiki/Beta-Version)

**Comment by hrhnick** [comment]
@donavanbecker 1.0.6-beta.2 now. The lock error from the bug report is gone, but I am seeing a new one now, not sure if it is related:

`[10/11/2022, 4:10:33 PM] [August] TypeError: Cannot read properties of undefined (reading 'retryCount')
[10/11/2022, 4:10:33 PM] [August] Lock: Front Door failed lockStatus (refreshStatus), Error Message: "Cannot read properties of undefined (reading 'retryCount')"`

**Comment by donavanbecker** [comment]
okay I pushed out another beta. Should be `v1.0.6-beta.3`

**Comment by hrhnick** [comment]
@donavanbecker beta 3 appears to be a regression. Back to the og errors regarding doorState

**Comment by donavanbecker** [comment]
lets try this next beta

**Comment by hrhnick** [comment]
Og error persists in beta.4 as well: [August] Lock: Front Door doorState: init, closed: false, open: false

**Comment by donavanbecker** [comment]
can you turn on debug logging so I can see more of the logging around this?

**Comment by hrhnick** [comment]
Let me know if you need the Lock Details from the debug as well, I can email that over.


```
[10/12/2022, 6:40:51 PM] [August] [DEBUG] Lock: Front Door battery (lockDetails): 30
[10/12/2022, 6:40:51 PM] [August] [DEBUG] Lock: Front Door currentFirmwareVersion (lockDetails): 1.1.10
[10/12/2022, 6:40:51 PM] [August] [DEBUG] Lock: Front Door parseStatus
[10/12/2022, 6:40:51 PM] [August] [DEBUG] Lock: Front Door BatteryLevel: 30, StatusLowBattery: 0
[10/12/2022, 6:40:51 PM] [August] Lock: Front Door doorState: init, closed: false, open: false
[10/12/2022, 6:40:51 PM] [August] [DEBUG] Lock: Front Door updateCharacteristic LockTargetState: 1
[10/12/2022, 6:40:51 PM] [August] [DEBUG] Lock: Front Door updateCharacteristic LockCurrentState: 1
[10/12/2022, 6:40:51 PM] [August] [DEBUG] Lock: Front Door updateCharacteristic BatteryLevel: 30
[10/12/2022, 6:40:51 PM] [August] [DEBUG] Lock: Front Door updateCharacteristic StatusLowBattery: 0
[10/12/2022, 6:40:51 PM] [August] [DEBUG] Lock: Front Door updateCharacteristic ContactSensorState: 1
```

**Comment by donavanbecker** [comment]
@hrhnick I got some pointers from the august-api repo owner. Let me try to make some enhancements and see if that helps.

**Comment by donavanbecker** [comment]
@hrhnick, can you test out the latest beta?

**Comment by hrhnick** [comment]
@donavanbecker things seem to be broken in beta.6. 
My MFA code was missing from my config, and even when I reenter my email/password, no MFA is sent to my email as expected on Homebridge restart.

```
[10/13/2022, 7:21:40 AM] Registering platform 'homebridge-august.August'
[10/13/2022, 7:21:40 AM] [August] Loaded homebridge-august v1.0.6-beta.6 child bridge successfully
[10/13/2022, 7:21:40 AM] Loaded 1 cached accessories from cachedAccessories.0E35D099345A.
[10/13/2022, 7:21:40 AM] [August] [DEBUG] Using Config Logging: debug
[10/13/2022, 7:21:40 AM] [August] [DEBUG] Finished initializing platform: August
[10/13/2022, 7:21:40 AM] [August] Platform Config: {"logging":"debug"}
[10/13/2022, 7:21:40 AM] [August] [DEBUG] Config OK
[10/13/2022, 7:21:40 AM] [August] [DEBUG] Using Default Refresh Rate (5 minutes).
[10/13/2022, 7:21:40 AM] [August] [DEBUG] Loading accessory from cache: Front Door
[10/13/2022, 7:21:40 AM] [August] [DEBUG] Executed didFinishLaunching callback
[10/13/2022, 7:21:40 AM] [August] [DEBUG] augustId: xxxx@xxxx.com, installId: undefined, password: xxxxxxx, isValidated: true
[10/13/2022, 7:21:40 AM] [August] Discover Devices: ReferenceError: Config errors found:
Missing config.installId or AUGUST_INSTALL_ID env var
```

**Comment by donavanbecker** [comment]
@hrhnick, can you repost your config?

**Comment by hrhnick** [comment]
@donavanbecker 

        {
            "name": "August",
            "credentials": {
                "augustId": "xxx@xxx.com",
                "password": "xxxxxxxxx.",
                "isValidated": true,
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "logging": "debug"
            },
            "platform": "August"
        },

**Comment by donavanbecker** [comment]
remove `isValidated` and try again

**Comment by hrhnick** [comment]
Got the MFA, and added it back in.


```
10/13/2022, 10:46:38 AM] [August] [DEBUG] August Credentials: {"config":{"apiKey":"xxx","pnSubKey":"xxx","installId":"xxx","idType":"email","augustId":"xxx@xxx.com","password":"xxx"}}
[10/13/2022, 10:46:38 AM] [August] [DEBUG] Lock: Front Door BatteryLevel: 30, StatusLowBattery: 0
[10/13/2022, 10:46:38 AM] [August] Lock: Front Door doorState: unknown, closed: undefined, open: undefined
[10/13/2022, 10:46:38 AM] [August] [DEBUG] Lock: Front Door updateCharacteristic LockTargetState: 1
[10/13/2022, 10:46:38 AM] [August] [DEBUG] Lock: Front Door updateCharacteristic LockCurrentState: 3
[10/13/2022, 10:46:38 AM] [August] [DEBUG] Lock: Front Door updateCharacteristic BatteryLevel: 30
[10/13/2022, 10:46:38 AM] [August] [DEBUG] Lock: Front Door updateCharacteristic StatusLowBattery: 0
[10/13/2022, 10:46:38 AM] [August] [DEBUG] Lock: Front Door updateCharacteristic ContactSensorState: 1
FetchError: Status 422 (98): Bridge is offline
[10/13/2022, 10:46:40 AM] [August] [DEBUG] Lock: Front Door lockStatus (refreshStatus): [Undefined]
[10/13/2022, 10:46:40 AM] [August] [DEBUG] Lock: Front Door lockStatus (refreshStatus): [Undefined]
[10/13/2022, 10:46:41 AM] [August] [DEBUG] Lock: Front Door lockDetails (refreshStatus): {"LockName":"Front Door","Type":5,"Created":"2022-03-30T01:35:33.563Z","Updated":"2022-03-30T01:35:33.563Z","LockID":"xxx","HouseID":"xxx","HouseName":"123 Main Street","Calibrated":false,"timeZone":"America/New_York","battery":0.3,"batteryInfo":{"level":0.3,"warningState":"lock_state_battery_warning_none","infoUpdatedDate":"2022-10-13T00:38:03.865Z","lastChangeDate":"2022-04-14T02:23:54.000Z","lastChangeVoltage":6558},"supportsEntryCodes":false,"remoteOperateSecret":"xxx","HomeKitSetupPayload":"X-HM://0066M05F45NMR","skuNumber":"AUG-SL05-M01-S01","macAddress":"xx:xx:xx:xx:xx:xx","SerialNumber":"xxxxx","LockStatus":{"status":"unknown","dateTime":"2022-10-13T14:46:39.294Z","isLockStatusChanged":false,"valid":true,"doorState":"unknown"},"currentFirmwareVersion":"1.1.10","homeKitEnabled":false,"zWaveEnabled":false,"isGalileo":false,"Bridge":{"_id":"xxxxx","mfgBridgeID":"xxxx","deviceModel":"august-lock","firmwareVersion":"1.1.10","operative":true,"status":{"current":"offline","lastOffline":"2022-10-13T14:46:40.444Z","updated":"2022-10-13T14:46:40.444Z","lastOnline":"2022-10-13T03:18:24.273Z"},"locks":[{"_id":"xxx","LockID":"xxx","macAddress":"xx:xx:xx:xx:xx:xx"}],"hyperBridge":true},"OfflineKeys":{"created":[],"loaded":[{"created":"2022-06-18T22:04:32.369Z","key":"xxx","slot":2,"UserID":"xxx","loaded":"2022-07-24T00:24:47.933Z"}],"deleted":[],"loadedhk":[{"key":"xxx","slot":257,"UserID":"xxx","created":"2022-03-30T01:35:33.573Z","loaded":"2022-03-30T01:35:56.142Z"}]},"parametersToSet":{},"users":{"xxxx":{"UserType":"superuser","FirstName":"xxx","LastName":"xxx","identifiers":["phone:+17742425609","email:xxx@xxx.com"]}},"pubsubChannel":"xxx","ruleHash":{},"cameras":[],"geofenceLimits":{"ios":{"debounceInterval":90,"gpsAccuracyMultiplier":2.5,"maximumGeofence":5000,"minimumGeofence":100,"minGPSAccuracyRequired":80}},"lockId":"xxx"}
[10/13/2022, 10:46:41 AM] [August] [DEBUG] Lock: Front Door battery (lockDetails): 30
[10/13/2022, 10:46:41 AM] [August] [DEBUG] Lock: Front Door currentFirmwareVersion (lockDetails): 1.1.10
[10/13/2022, 10:46:41 AM] [August] [DEBUG] Lock: Front Door parseStatus
```

**Comment by donavanbecker** [comment]
@hrhnick I did get that two but then it went away. I will keep researching

**Comment by ahumaydan** [comment]
I'm receiving the same issue except I do not have DoorSense installed (nor did I ever have it installed)

**Comment by ahumaydan** [comment]
I updated to v1.0.6 beta 10 and still see the issue

**Comment by donavanbecker** [comment]
sorry haven't really had time to look into this.

**Comment by jlg89** [comment]
IMO the cleanest way to handle this would be for the plugin to disregard contact sensor data altogether if the optional "hide_contactsensor" flag is set, i.e. don't even try to pull it from the mothership. In my case, I've set it, and am seeing the errors in the log (I'm not on the beta), which tells me that the plugin currently only uses the hide_contactsensor flag for publishing control, not for pulling data.

<pre>
{
    "platform": "August",
    "name": "August",
    "credentials": {
        "augustId": "xxx@xxx",
        "password": "xxxxxxxx",
        "validateCode": "xxxxxxxx"
    },
    "options": {
        "devices": [
            {
                "lockId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "hide_device": false,
                "lock": {
                    "hide_contactsensor": true
                }
            }
        ]
    }
}
</pre>

**Comment by ahumaydan** [comment]
The latest beta plus @jlg89 's config solved the issue

**Comment by dacarson** [comment]
FWIW, I don't have DoorSense configured, and with the latest beta I don't see this issue.

**Comment by jlg89** [comment]
Also FWIW, I had to switch to using the SmartThings integration, in order to get all seven of the locks in my facility working at once (see [here](https://github.com/donavanbecker/homebridge-august/issues/55#top)) and what I see in the logs of the [SmartThings plugin](https://github.com/iklein99/homebridge-smartthings) is that, once it detects this DoorSense error a few times, it automatically disables it for that lock. So, in terms of this plugin, it would essentially have to toggle the "hide_contactsensor" boolean on the fly as a non-persistent setting.

**Comment by dacarson** [comment]
One of the major issues is that [homebridge-august](https://github.com/donavanbecker/homebridge-august) makes 2 calls to the August API for every lock status update. It first calls for the [lockStatus](https://github.com/hufftheweevil/august-api/blob/ffcf2c51f0a8aedb86aa69c4d3a8412525eb1c56/definitions.md?plain=1#L96) and then calls for the [lockDetails](https://github.com/hufftheweevil/august-api/blob/ffcf2c51f0a8aedb86aa69c4d3a8412525eb1c56/definitions.md?plain=1#L13). Almost all of the data in 'lockStatus' is also available in 'lockDetails', with the exception of [lockStatus state](https://github.com/hufftheweevil/august-api/blob/ffcf2c51f0a8aedb86aa69c4d3a8412525eb1c56/definitions.md?plain=1#L126), which can be easily fixed in this library, but also [lockStatus retryCount](https://github.com/hufftheweevil/august-api/blob/ffcf2c51f0a8aedb86aa69c4d3a8412525eb1c56/definitions.md?plain=1#L122) which I don't see a fix for. The 'retryCount' field is used to indicate if the lock is jammed or not.

BTW, it is easy to determine if a lock has DoorSense or not. In [lockStatus door](https://github.com/hufftheweevil/august-api/blob/ffcf2c51f0a8aedb86aa69c4d3a8412525eb1c56/definitions.md?plain=1#L120C7-L120C7) it shows `kAugDoorState_Init` and in [lockDetails lockStatus doorState](https://github.com/hufftheweevil/august-api/blob/ffcf2c51f0a8aedb86aa69c4d3a8412525eb1c56/definitions.md?plain=1#L45) it shows `init`.

**Comment by jlg89** [comment]
Is it actually homebridge-august making the calls, or the august-api module?

**Comment by dacarson** [comment]
It is actually homebridge-august.

I see homebridge-august making these calls to august-api when it refreshes the [state of the lock](https://github.com/donavanbecker/homebridge-august/blob/8d3fa90c233b7f9cf43a9996805254d28dc3cff2/src/devices/lock.ts#L216):
[lockStatus](https://github.com/donavanbecker/homebridge-august/blob/8d3fa90c233b7f9cf43a9996805254d28dc3cff2/src/devices/lock.ts#L220):
`const lockStatus = await this.platform.august.status(this.device.lockId);`
which calls through to the august-api status object, which then does this:
`let { body } = await this.put(`/remoteoperate/${lockId}/status`)`
and
[lockDetails](https://github.com/donavanbecker/homebridge-august/blob/8d3fa90c233b7f9cf43a9996805254d28dc3cff2/src/devices/lock.ts#L239):
`const lockDetails = await this.platform.august.details(this.device.lockId);`
which calls through to august-api details object, which then does this:
`let { body } = await this.get(`/locks/${lockId}`)`

**Comment by donavanbecker** [comment]
@dacarson Would you post a PR for a fix on this based on the beta branch?

**Comment by dacarson** [comment]
I'll create a new issue to reduce the number of calls to August API, and leave this one as depending on the number of locks, this may still be an issue.

**Comment by dacarson** [comment]
I think this issue should be moved to verify (is that a state?) or closed. With the ability to hide the contact sensor, I don't see this issue anymore. Though I would recommend that the Readme be updated to tell people what to do if they don't have DoorSense.

**Comment by jlg89** [comment]
I agree, this issue is really separate from the API calls issue, as it only deals with the handling of DoorSense errors. It's my fault that these got conflated, I didn't make it clear enough that I only mentioned the API calls issue because that's what drove me to use the SmartThings plugin, which is where I noticed the interesting way they handle DoorSense errors.

**Comment by donavanbecker** [comment]
please try the latest beta.

**Comment by donavanbecker** [comment]
v1.2.0 has been released
